<section class="bets-sellers">
    <div class="top">
        <h1 class="title">Mais Vendidos</h1>
        <div class="left">
            <a href="#" class="bets">ver mais produtos</a>
            <i class="fas fa-plus"></i>
        </div>
    </div>

    <div class="list-products">

        <div class="card">
            <div class="image">
                <div class="discount">
                    <span class="value-discount">20%</span>
                    <span class="text">Off!</span>
                </div>
                <img src="<?=$this->getViewFileUrl('Magento_Cms::images/1.png'); ?>" alt="Image">
                <img style="display: none;" src="<?=$this->getViewFileUrl('Magento_Cms::images/1.hover.png'); ?>" alt="Image">
            </div>
            <div class="description">
                <div class="start">
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star desable"></i>
                    <i class="fas fa-star desable"></i>
                </div>
                <p class="title">Tênis Adidas Originais Multix</p>
                <div class="prices">
                    <small class="price-old">R$ 166,00</small>
                    <span class="price-new">R$ 150,00</span>
                </div>
                <p class="sub-title">em até <b>6x</b> de <b>R$ 25,00</b> no cartão</p>
            </div>
        </div>

        <div class="card">
            <div class="image">
                <div class="discount">
                    <span class="value-discount">20%</span>
                    <span class="text">Off!</span>
                </div>
                <img src="<?=$this->getViewFileUrl('Magento_Cms::images/1.png'); ?>" alt="Image">
                <img style="display: none;" src="<?=$this->getViewFileUrl('Magento_Cms::images/1.hover.png'); ?>" alt="Image">
            </div>
            <div class="description">
                <div class="start">
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star desable"></i>
                    <i class="fas fa-star desable"></i>
                </div>
                <p class="title">Tênis Adidas Originais Multix</p>
                <div class="prices">
                    <small class="price-old">R$ 166,00</small>
                    <span class="price-new">R$ 150,00</span>
                </div>
                <p class="sub-title">em até <b>6x</b> de <b>R$ 25,00</b> no cartão</p>
            </div>
        </div>

        <div class="card">
            <div class="image">
                <div class="discount">
                    <span class="value-discount">20%</span>
                    <span class="text">Off!</span>
                </div>
                <img src="<?=$this->getViewFileUrl('Magento_Cms::images/1.png'); ?>" alt="Image">
                <img style="display: none;" src="<?=$this->getViewFileUrl('Magento_Cms::images/1.hover.png'); ?>" alt="Image">
            </div>
            <div class="description">
                <div class="start">
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star desable"></i>
                    <i class="fas fa-star desable"></i>
                </div>
                <p class="title">Tênis Adidas Originais Multix</p>
                <div class="prices">
                    <small class="price-old">R$ 166,00</small>
                    <span class="price-new">R$ 150,00</span>
                </div>
                <p class="sub-title">em até <b>6x</b> de <b>R$ 25,00</b> no cartão</p>
            </div>
        </div>

        <div class="card">
            <div class="image">
                <div class="discount">
                    <span class="value-discount">20%</span>
                    <span class="text">Off!</span>
                </div>
                <img src="<?=$this->getViewFileUrl('Magento_Cms::images/1.png'); ?>" alt="Image">
                <img style="display: none;" src="<?=$this->getViewFileUrl('Magento_Cms::images/1.hover.png'); ?>" alt="Image">
            </div>
            <div class="description">
                <div class="start">
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star enable"></i>
                    <i class="fas fa-star desable"></i>
                    <i class="fas fa-star desable"></i>
                </div>
                <p class="title">Tênis Adidas Originais Multix</p>
                <div class="prices">
                    <small class="price-old">R$ 166,00</small>
                    <span class="price-new">R$ 150,00</span>
                </div>
                <p class="sub-title">em até <b>6x</b> de <b>R$ 25,00</b> no cartão</p>
            </div>
        </div>

    </div>
</section>
