<section class="bets-sellers">
    <div class="top">
        <h1 class="title">Mais Vendidos</h1>
        <div class="left">
            <a href="#" class="bets">ver mais produtos</a>
            <i class="fas fa-plus"></i>
        </div>
    </div>

    <div class="list-products">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bets-sellers')->toHtml(); ?>
    </div>
</section>
