<section class="footer">
    <div class="row">
        <div class="col logo">
            <img
                class="img"
                src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
                title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
                alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            />
            <p class="text">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
            </p>
        </div>
        <div class="col map-site">
            <div class="row">
                <div class="col">
                    <h4 class="title">Institucional</h4>
                    <a href="#" class="link">Sobre a empresa</a>
                    <a href="#" class="link">Nossos produtos</a>
                    <a href="#" class="link">Trabalhe conosco</a>
                    <a href="#" class="link">Conheça nossa loja</a>
                </div>
                <div class="col">
                    <h4 class="title">Minha conta</h4>
                    <a href="#" class="link">Dados pessoais</a>
                    <a href="#" class="link">Alterar senha</a>
                    <a href="#" class="link">Meus pedidos</a>
                    <a href="#" class="link">Endereço de entrega</a>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h4 class="title">Dúvidas</h4>
                    <a href="#" class="link">Forma de envio</a>
                    <a href="#" class="link">Forma de pagamento</a>
                    <a href="#" class="link">Garantia de segurança</a>
                    <a href="#" class="link">Orçamentos</a>
                </div>
                <div class="col">
                    <h4 class="title">Contato</h4>
                    <a href="#" class="link"><i class="fab fa-whatsapp"></i> 21 9 8096-9124</a>
                    <a href="#" class="link"><i class="fas fa-map-marker-alt"></i> Eulina Ribeiro 100</a>
                    <a href="#" class="link"><i class="fas fa-envelope"></i> hypeconect@gmail.com</a>
                </div>
            </div>
        </div>
        <div class="col social">
            <div class="face-curti">
                <img class="img" src="<?= $this->getViewFileUrl('Magento_Cms::images/face.png'); ?>" alt="Banner" />
                <div class="social">
                    <a href="#" class="fab fa-instagram"></a>
                    <a href="#" class="fab fa-facebook-square"></a>
                </div>
            </div>
        </div>
    </div>

</section>
