<section class="footer-end">
    <div class="row">
        <div class="col payment">
            <div class="col payments">
                <p class="text">Formas de Pagamento</p>
                <hr>
                <div class="images">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/flags-a.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/flags-b.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/flags-c.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/flags-d.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/flags-e.png'); ?>" alt="">
                </div>
            </div>
            <div class="col delivery">
                <p class="text">Formas de Entrega</p>
                <hr>
                <div class="images">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/delivery-a.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/delivery-b.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/delivery-c.png'); ?>" alt="">
                </div>
            </div>
            <div class="col security">
                <p class="text">Segurança e Certificação</p>
                <hr>
                <div class="images">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/security-a.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/security-b.png'); ?>" alt="">
                    <img src="<?= $this->getViewFileUrl('Magento_Cms::images/security-c.png'); ?>" alt="">
                </div>
            </div>
        </div>
        <div class="col address">
            <p class="text">Razão Social -CNPJ 123456456.545/000 | Endereço físico, 12345 | Bairro | Cidade - Estado | CEP 86600-000</p>
            <hr>
        </div>
        <div class="col appeal">
            <img src="<?= $this->getViewFileUrl('Magento_Cms::images/bis2bis.png'); ?>" alt="">
            <p class="text">Crie sua loja virtual com a melhor empresa de e-commerce do Brasil</p>
        </div>
    </div>
</section>
