<nav class="navbar">
    <div class="container">
        <div class="division"></div>
        <ul class="links">
            <li class="navs"><a href="" class="link">Roupas</a></li>
            <li class="navs"><a href="" class="link">Tênis</a></li>
            <li class="navs"><a href="" class="link">Vestuário Masculino</a></li>
            <li class="navs"><a href="" class="link">Vestuário Feminino</a></li>
        </ul>
    </div>
</nav>
