<section class="newsletter">
    <div class="container">
        <div class="icon"><i class="fas fa-envelope"></i></div>
        <div class="titles">
            <p class="text">Cadastre-se em nossa</p>
            <h4 class="title">Newsletter</h4>
        </div>
        <div class="description">
            <p class="text">ganhe <span class="text">10% de desconto</span></p>
            <span class="text">na sua primeira compra</span>
        </div>
        <div class="form">
            <input type="email" placeholder="Digite seu email" class="input">
            <div class="inputb">
                <input type="text" placeholder="Digite seu nome" class="input">
                <button class="btn">Enviar</button>
            </div>
        </div>
    </div>
</section>
